### PR TITLE
reduce number of url dependencies, update url

### PR DESCRIPTION
**Pull request by drahnr**
mozilla/sccache#683

Must be refactored or squashed

### CODE REVIEW

**Review by TriplEight — APPROVED** [review]
:+1:

**Comment by Xanewok** [comment]
Can we close this since https://github.com/paritytech/sccache/pull/41 is merged?

**Comment by drahnr** [comment]
These changes are not upstream afaik

**Comment by Xanewok** [comment]
See https://github.com/mozilla/sccache/commit/185c6ba4b0d360e6be8daf15a9fb80899c030df5 and https://github.com/mozilla/sccache/commit/3c45df0fbe3259a4851f47c50c9d75d54a82fc7b, we synced to that with #41

**Comment by drahnr** [comment]
I saw one commit that introduced a few new error variants for better `ring` errors (which has an arguably questionable error policy).

**Pull request closed without merging**
