### PR TITLE
Legacy rebased

### PR DESCRIPTION
**Pull request by drahnr**
All those old changes...

### CODE REVIEW

**Comment by Xanewok** [comment]
This was split into:
- https://github.com/paritytech/sccache/pull/64 (merged)
- https://github.com/paritytech/sccache/pull/65 (merged)
- https://github.com/paritytech/sccache/pull/66 (pending review)
- https://github.com/paritytech/sccache/pull/67 (pending review)

and I skipped some minor things like extraneous `clippy::...` annotations, `fs::metadata` reshufflings in tests or reverting changes that were done upstream in the meantime (e.g. reintroducing `ServerNonce::from_rng`)

When the last aforementioned PRs are merged, I'd say we can safely close this and remove the branch.

**Comment by drahnr** [comment]
I'd like to keep the test assert cleanup, the rest can happily bite the dust - the whole clippy lint topic should be dealt with in a separate PR.

**Comment by drahnr** [comment]
I'd also wait until the PRs are merged and see what effective delta is left, so we can then start new PRs based on those hints

**Comment by Xanewok** [comment]
I created a delta between what'll be merged with those 4 PRs and what was left in `legacy-rebased`: https://commie.io/#5Jpe4qwN. Each change contains a rationale behind it.

> I'd like to keep the test assert cleanup (...)

I can submit a PR reintroducing it if you feel strongly about it, but here are some of my thoughts (note more or less copied from the linked delta) and the change discussed:
```diff
         // Ensure that the object file was created.
-        assert!(0 < fs::metadata(&obj).unwrap().len());
+        assert!(fs::metadata(&obj).map(|m| m.len() > 0).unwrap());
```
I really don't think it pulls its weight at the cost of increasing divergence and growing the diff between forks. It's basically unwrapping first, rather than `map`ping the value undearneath, coupled with reverse, almost C/C++ yoda-style comparison.

If we want to increase legiblility/benefit, we should either
1. switch around the sides of the comparison to read more naturally or
2. somehow assert that `fs::metadata(&obj).map(|m| m.len())` matches `Ok(1..)` or `Ok(val) if val > 0` to get more info reported by the macro in case we encounter an `Err`
3. (optionally coupled with `assert_ne!` in both of the cases)

Until then, it just feels like switching around without any benefit (at least it makes it harder for me to read) while costing us a maintenance effort to keep this difference between the forks.

Let me know if I'm too much in the weeds on this one; I'd happily just skip the change altogether.

**Comment by drahnr** [comment]
I agree, the current change is insignificant and `assert_matches!(fs::meta(), Ok(1..))` is a way prettier approach anyways!

**Comment by drahnr** [comment]
Alright, this is done then :wave:

**Pull request closed without merging**
