### PR TITLE
chore: add a localhost dummy config

### PR DESCRIPTION
**Pull request by drahnr**
Add a demo config for the dist setup.

### CODE REVIEW

**Review by General-Beck — COMMENTED** [review]
Enviroment=SCCACHE_NO_DAEMON=1
I would like to see these environment variables in a separate configuration file. More precisely, all environment variables in general. To avoid such constructs `SCCACHE=bla-blah-bla sccache`. You need a clear sccache_config.toml file with a description of all available options and environment variables. And it had priority over running from the command line.
@drahnr we have been asking developers to implement this for a long time. The configuration file is very important for automation. Is it possible to implement this at this stage?

**Comment by drahnr** [comment]
@General-Beck #2 should cover that?

**Comment by General-Beck** [comment]
cool, but it's important to know that the configuration file has maximum priority over environment variables. We encounter this very often, especially in environments that run locally. For example, the priority of an already running sccache process that takes old variables after restarting.

**Comment by TriplEight** [comment]
Can it be optimized a bit with the according to changes in #2 ?

**Comment by General-Beck** [comment]
and I think it's possible to create config_example. toml

**Comment by General-Beck** [comment]
if we resolve this issue (config file) at this stage, there will be less disagreement in the future

**Comment by drahnr** [comment]
The normal logic that I would expect is read `config.toml`, overwrite with `env`, overwrite with explicit `cli` flags. And this is also the case for sccache, there are a few flags that have env vars but no flags or config entries associated to them.

**Comment by TriplEight** [comment]
I think it lacks some ELotEOLs and good to go, as far as I'm understanding.
Do the docs have to be updated?

**Comment by Xanewok** [comment]
It seems this was already merged but I'm not sure if the discussion around this was eventually resolved. Since then we rebased our `master` and started incrementally merging our changes again, so I'd like to close this as a dupe and redirect any further discussion to #66 if possible.

Please reopen if you'd like to rebase/force-push and continue the discussion here, instead.

**Pull request closed without merging**
